apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::770132776547:user/terraform-shopstack
      username: terraform-shopstack
      groups:
        - system:masters
  mapRoles: |
    - rolearn: arn:aws:iam::770132776547:role/YOUR_NODE_INSTANCE_ROLE
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
